name: supabase
description: A dart client library for Supabase.
version: 0.0.1-dev.1
homepage: "https://supabase.io"
repository: "https://github.com/supabase/supabase-dart"

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  gotrue: ^0.0.1-dev.4
  postgrest: ^0.0.4
  realtime_client: ^0.0.1-dev.4

dev_dependencies:
  test: ^1.15.4
  lint: ^1.3.0
